version: '2'
services:
    app_1:
        restart: always
        image: 'travel_app:TEST_3.6'
        env_file: .env.release
        ports:
            - '30019:3001'
        networks:
            - app_mysql_innout_networks

networks:
    app_mysql_innout_networks:
        external: true
